server:
  port: 8088

spring:
  application:
    name: c-shopper
  profiles:
    active: dev

---
#Dev Profile
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/c_shopper?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update


---
#Prod Profile
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/c_shopper?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update


